services:
  flask-app-template:
    image: mzvlsmxx/flask-app-template:v0.0.0
    container_name: flask-app-template
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=777
      - APP_DEBUG=True
      - REDIS_HOST=flask-app-template-redis
      - REDIS_PORT=6379
      - MYSQL_HOST=flask-app-template-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWD=passwd
    ports:
      - "777:777"
    depends_on:
      - flask-app-template-redis
      - flask-app-template-mysql
    networks:
      - flask-app-template-network

  flask-app-template-redis:
    image: redis:7.0-alpine
    container_name: flask-app-template-redis
    ports:
      - "778:6379"
    networks:
      - flask-app-template-network

  flask-app-template-mysql:
    image: mysql:8.0.44-debian
    container_name: flask-app-template-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
    ports:
      - "779:3306"
    networks:
      - flask-app-template-network

networks:
  flask-app-template-network:
    name: flask-app-template-network
    driver: bridge